### ISSUE TITLE
[Draft] Keep track of students certificate eligibility in the portal

### ISSUE THREAD

**Issue by dbsousa01** [LDSSA/portal#161] opened 2021-08-26 19:44 UTC
Description: It would be useful to know which students are no longer eligible or have given up on the course so we know which ones should complete the SLUs before the Hackathons. We know this info since we know what has been submitted and what the grades are.
This would help student success knowing who to chase - grooming needed by @rjna for specific specs

**Comment by CatarinaSilva** [comment] 2021-08-28 11:31
I've proposed a solution iin #149

**Comment by hcastilho** [comment] 2021-09-09 18:38
Closing as duplicate of #149

**Closed by hcastilho** 2021-09-09 18:38 UTC
Labels: enhancement, back office, needs grooming
