### ISSUE TITLE
Draft: Payment proof uploads unintuitive

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#128] opened 2021-07-07 18:14 UTC
There's an upload and a submit button which is a bad.
Replace with on one button that uploads and submits.

**Comment by cimendes** [comment] 2021-08-09 17:59
Duplicate of #119 ?

**Comment by cimendes** [comment] 2021-08-19 19:13
Closing as it's a duplicate issue

**Closed by cimendes** 2021-08-19 19:13 UTC
